version: "1.0"
services:
  localstack:
    image: localstack/localstack:0.12.12
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ".​​​​/ls_tmp:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true