spring:
  rabbitmq:
    password: guest
    host: 127.0.0.1
    port: '5672'
    username: guest

  cloud:
    stream:
      bindings:
        commentCreated-out-0:
          group: eventsGroup
          destination: comment
        commentUpdated-out-0:
          destination: comment
          group: eventsGroup
        articleUpdated-out-0:
          group: eventsGroup
          destination: article
        commentDeleted-out-0:
          destination: comment
          group: eventsGroup
        userCreated-out-0:
          group: eventsGroup
          destination: user
        emailSend-out-0:
          destination: email
          group: send
        articleCreated-out-0:
          group: eventsGroup
          destination: article

        createdEventConsumer-in-0:
          destination: user,article,comment
          group: eventsGroup
        emailSendConsumer-in-0:
          destination: email
          group: send

      rabbit:
        bindings:
          articleCreated-out-0:
            producer:
              routing-key-expression: '"article.created"'
          commentDeleted-out-0:
            producer:
              routing-key-expression: '"comment.deleted"'
          userCreated-out-0:
            producer:
              routing-key-expression: '"user.created"'
          emailSend-out-0:
            producer:
              routing-key-expression: '"email.send"'
              exchange-type: direct
          articleUpdated-out-0:
            producer:
              routing-key-expression: '"article.updated"'
          commentCreated-out-0:
            producer:
              routing-key-expression: '"comment.created"'
          commentUpdated-out-0:
            producer:
              routing-key-expression: '"comment.updated"'

          createdEventConsumer-in-0:
            consumer:
              queueNameGroupOnly: true
              bindQueue: true
              bindingRoutingKey: #.created
          emailSendConsumer-in-0:
            consumer:
              bindingRoutingKey: '"email.send"'
              exchange-type: direct

    function:
      definition: createdEventConsumer;emailSendConsumer
